#! /bin/bash

if [ "$3" != "$4" ]
then
  echo "+$3/-$4"
  ./game boards.dat $6 "$1" "$3" "$2" "$4" 1 "$5"
  echo "-$3/+$4"
  ./game boards.dat $6 "$2" "$4" "$1" "$3" 1 "$5"
else
  echo "+$3/-$3"
  ./game boards.dat $6 "$1" "$3" "$1" "$3" 1 "$5"
fi
